package com.ecommerce.catalog.application.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record ProductResponse(
    UUID id,
    UUID sellerId,
    String name,
    String slug,
    String description,
    String descriptionHtml,
    BigDecimal price,
    BigDecimal compareAtPrice,
    BigDecimal costPerItem,
    int stockQuantity,
    int lowStockThreshold,
    String sku,
    String barcode,
    UUID categoryId,
    String categoryName,
    List<String> tags,
    String status,
    boolean isFeatured,
    String visibility,
    String metaTitle,
    String metaDescription,
    BigDecimal averageRating,
    int reviewCount,
    BigDecimal weightKg,
    String weightUnit,
    String imageUrl,
    String threeDModelUrl,
    List<ProductImageResponse> images,
    Instant createdAt,
    Instant updatedAt
) {}
